#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login_check:
  path: /login
  methods: ['POST']

register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: ['POST']
